version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: root
      POSTGRES_PASSWORD: adminuser12_
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node:
    build:
      context: ./user-app
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://root:adminuser12_@postgres:5432/user
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node

volumes:
  postgres_data:
