version: '1'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: root
      POSTGRES_PASSWORD: adminuser12_
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node:
    build:
      context: ./user-app
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://root:adminuser12_@postgres:5432/user
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: user
      DB_USER: root
      DB_PASSWORD: adminuser12_
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev

volumes:
  postgres_data:
