name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VM
      env:
        VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        VM_USER: ${{ secrets.VM_USER }}
        VM_HOST: ${{ secrets.VM_HOST }}
      run: |
        # SSH ke VM
        ssh -i $VM_SSH_KEY $VM_USER@$VM_HOST << EOF
          cd /itd/backend-identify
          
          git pull
          
          docker-compose down
          
          docker-compose build
          
          docker-compose up -d
        EOF