name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.VM_SSH_KEY }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          cd /itd/backend-identify
          
          git pull origin master
        EOF
