name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

      - name: Deploy to VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        run: |
          # Setup SSH Agent and add private key
          eval $(ssh-agent -s)
          echo "$VM_SSH_PRIVATE_KEY" | ssh-add -

          # SSH ke VM dan jalankan perintah deploy
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST << EOF
            cd /itd/backend-identify

            # Tarik image dari GHCR dan jalankan ulang container
            docker pull ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
            
            docker-compose down
            
            docker-compose up -d
          EOF
