name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
      echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
        cd /itd/backend-identify
        git pull origin master
      EOF

