name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload code to VM
      run: |
        scp -i ${{ secrets.VM_SSH_KEY }} -r ./user-app ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/itd/backend-identify

    - name: Deploy to VM
      run: |
        ssh -i ${{ secrets.VM_SSH_KEY }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          # Pindah ke direktori proyek di VM
          cd /itd/backend-identify

          # Hapus container lama jika ada
          docker-compose down

          # Bangun image Docker di VM
          docker-compose build

          # Jalankan container dengan image terbaru
          docker-compose up -d
        EOF
